### ISSUE TITLE
Any way to check the current "Folder"

### ISSUE THREAD

**Issue by madman2021** [Mountain-BC/DisplayPad.SDK.Demo#2]
Having a quick look through the SDK I can't see a way to get the current folder.

If I wanted my code to only trigger when the DisplayPad is in a specific folder I would need to get the current folder name or id

**Comment by ravi-devitpl** [comment]
Hi @madman2021,

To get the current folder you need to do it with your code. From the SDK you can get only the key press event of a specific key.
You can save the binding status and other information related to specific button and utilize the key event to get what kind of binding was there. 
I hope it helps.

Thanks!
