### ISSUE TITLE
KeyMatrix Question

### ISSUE THREAD

**Issue by Neuffexx** [Mountain-BC/DisplayPad.SDK.Demo#6]
Was checking out how the ID's are set up for the Keys.
Was simply wondering if there is a reason that the last Key's ID is `14*9-1` rather than `12*9-1`?
![image](https://github.com/Mountain-BC/DisplayPad.SDK.Demo/assets/63469833/5ba434f5-8c93-4d70-ba83-136b31b98612)

**Comment by AshishSrivastavaDevit** [comment]
In this, how the key mapped in the hardware is depend on the matrix table. Please see the table for DisplayPad in below.

![image](https://github.com/Mountain-BC/DisplayPad.SDK.Demo/assets/98343452/8c1172af-5995-42da-a281-c53f704df200)

**Comment by Neuffexx** [comment]
Understood, then additionally I wanted to ask more questions, but I think its better I open a new question for it.
